language: go

sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - go get -t -u github.com/dingdayu/golangtools/example/config

script:
  - export PATH="$PATH:$HOME/gopath/bin"
  - make test