version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\dingdayu\golangtools

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.9

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  # - choco install bzr
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files\Mercurial\%Path%
  - go version
  - go get -u github.com/golang/dep/cmd/dep
  - go env

build: false
deploy: false

test_script:
  - cd example\config
  - dep ensure
  - go build
  - dir /a *
  - config.exe -c conf.json