version: "{build}"

# doc: https://www.appveyor.com/docs/appveyor-yml/

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

# Skipping commits with particular message or from specific user
skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif|md)/      # Regex for matching commit message


# Source Config
clone_folder: c:\gopath\src\github.com\dingdayu\golangtools

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.9

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  # - choco install bzr
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files\Mercurial\%Path%
  - go version
  - go get -u github.com/golang/dep/cmd/dep
  - go env

build: false
deploy: false

test_script:
  - cd example\config
  - dep ensure
  - go build
  - dir /a *
  - config.exe -c conf.json

notifications:

  # Email
  - provider: Email
    to:
      - 614422099@qq.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true